### ISSUE TITLE
Can't create an account

### ISSUE THREAD

**Issue by girotrakaran** [AVatch/uni-bug-tracker#1]
The submit button at the bottom does not get active-- even after entering all required information correctly. I tried on safari and chrome. 

I used the correct email address (on which i received the invitation).

**Comment by AVatch** [comment]
Hey there! I’ll take a look at this. It may also be that the password and password confirm did not match but that should be communicated

**Comment by AVatch** [comment]
Hey there just want to loop in did you manage to get this working?
