### ISSUE TITLE
Adding ideas/adding people on ideas on Microsoft Edge caused nothing to be added to ideas

### ISSUE THREAD

**Issue by qxzsilver1** [AVatch/uni-bug-tracker#13]
I tried to add a few ideas, as well as add an idea with people from my #dreamteam.  However, this wasn't properly added (although the GUI on Microsoft Edge indicated as if it was actually added).  The number of ideas also was not reflective of actual total number of ideas generated by students in the class.  I noticed that in Google Chrome this was fine.  Afterwards, I also opened up the same link in Microsoft Edge again and the total number of ideas was updated.

This may have been a temporary buffering or server issue.

**Comment by AVatch** [comment]
I’m pushing an update :) that’s prob it. But I’ll check for any errors!

TTFN,
Adrian V

On Sep 18, 2018, at 10:49 PM, qxzsilver1 <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried to add a few ideas, as well as add an idea with people from my #dreamteam. However, this wasn't properly added (although the GUI on Microsoft Edge indicated as if it was actually added). The number of ideas also was not reflective of actual total number of ideas generated by students in the class. I noticed that in Google Chrome this was fine. Afterwards, I also opened up the same link in Microsoft Edge again and the total number of ideas was updated.

This may have been a temporary buffering or server issue.
