### ISSUE TITLE
Adding Details outside of the Question interface

### ISSUE THREAD

**Issue by dhruvjain1318** [AVatch/uni-bug-tracker#14]
Hi,

I can't seem to be able to add details when I click on a loose idea, or an idea outside of the question interface. If I just click on a loose idea, the following happens:

From loose idea, click "fill out details:
![image](https://user-images.githubusercontent.com/40001480/45922856-2980fa80-bea5-11e8-971e-aafc7abbfc88.png)

Then:
![image](https://user-images.githubusercontent.com/40001480/45922862-49182300-bea5-11e8-9d29-82698240075f.png)

However, if I do it from the question interface:
![image](https://user-images.githubusercontent.com/40001480/45922870-6ea52c80-bea5-11e8-9242-42437b231912.png)

Then pick an idea:
![image](https://user-images.githubusercontent.com/40001480/45922874-8381c000-bea5-11e8-8418-300be84ac6ec.png)

The available details show up just fine. This makes it hard to do details on anything other than the first 40 or so ideas on a question. Can't really add details to the ideas I like and find through search.

Thanks!

**Comment by AVatch** [comment]
Thanks for opening this - this is a ux issue on us. We’re working on cleaning it up. The details are scoped to a question so they only appear on ideas tied to that question. Loose ideas are not part of a question so they don’t need those details.
