### ISSUE TITLE
clicking on someone's name brings up prompt to remove them

### ISSUE THREAD

**Issue by eeyan** [AVatch/uni-bug-tracker#15]
<img width="394" alt="screen shot 2018-09-23 at 10 35 33 pm" src="https://user-images.githubusercontent.com/607319/45936150-425ede00-bf81-11e8-8232-8b2666e2575e.png">
Don't know if it works, but this prompt comes up when it definitely shouldn't.

**Comment by AVatch** [comment]
Thanks for reporting that - this is meant to be for managing the people in the future. I assume you are trying to use it to search for the user. 

We need to communicate the two clearly and we need to get our search interface sorted out so you can use it.

For now if you click on the search icon and type a persons name / email then click on them you should see all their posts

**Comment by eeyan** [comment]
I haven't tried it, but I assume a normal user like me shouldn't be able to remove other users? I heard of someone being removed from the future and unable to add their ideas, and I thought this might have been what caused it.

**Comment by AVatch** [comment]
Yup that’s why we added the confirm to prevent accidental removes. 

We are giving the benefit of the doubt that no one will do anything silly. 

That being said this is utility functionality which will be required down the line but it’s not really the focus of the product so we are punting on it till we have the bandwidth to do a proper pass. 

Hopefully that will be soon as we grow the team :)
