### ISSUE TITLE
Details options not available

### ISSUE THREAD

**Issue by qxzsilver1** [AVatch/uni-bug-tracker#18]
When trying to go into an idea and add different detail options (Angel, Devil, Bigger, etc.), it doesn't show up:

![image](https://user-images.githubusercontent.com/22142925/46056283-ef6e5d80-c11d-11e8-9df7-5685d2893348.png)

![image](https://user-images.githubusercontent.com/22142925/46056307-fb5a1f80-c11d-11e8-8719-5f259c5abb31.png)

**Comment by AVatch** [comment]
Hey there make sure that the idea is associated with the question that has those details.

**Comment by AVatch** [comment]
Hey there - the detail options should now be available!
