### ISSUE TITLE
Adding people to idea not working

### ISSUE THREAD

**Issue by qxzsilver1** [AVatch/uni-bug-tracker#19]
I added the following people but they don't show up as part of my added members:

![image](https://user-images.githubusercontent.com/22142925/46056880-dca95800-c120-11e8-98c5-1480661b6c3f.png)

**Comment by AVatch** [comment]
Hey there thanks for this - I am looking into it as others have reported this bug.

**Comment by AVatch** [comment]
Hey there - I just pushed out an update which should address this. Let me know if you find the issue to persist. (fix is applied to build 1.0.0-b.67)
