### ISSUE TITLE
back icon not working

### ISSUE THREAD

**Issue by alicekamens** [AVatch/uni-bug-tracker#20]
Once I click into an idea, if I want to go back to Startup Ideas future, the back icon doesn't work. Nothing happens when I click it. In attached screenshot I'm talking about the < symbol next to Startup Ideas 2018. Is this a browser issue? I'm using chrome.

![screen shot 2018-09-26 at 10 21 04 am](https://user-images.githubusercontent.com/40778946/46086360-ea3cfd00-c175-11e8-9869-aab0fbbc4f9a.png)

**Comment by AVatch** [comment]
Thanks! I’ll take a look! We just pushed an update that deals with navigation last night so it may be a bug that snuck in

**Comment by AVatch** [comment]
Hey there! We spent the last few days going over navigation and cleaning it up. This should work as expected now, but if not feel free to re-open!
