### ISSUE TITLE
Question prompt truncated in dropdown when creating new idea

### ISSUE THREAD

**Issue by irishroryc** [AVatch/uni-bug-tracker#25]
I can't see what question I'm setting on new ideas since the text is truncated.

![question_truncated](https://user-images.githubusercontent.com/20443817/46181543-7f361800-c294-11e8-94ac-d8234b1491f9.JPG)

**Comment by AVatch** [comment]
Thanks for this - it’s on the list of things to style this properly !

**Comment by AVatch** [comment]
Thanks - the text no longer truncates, but wraps. Lots to do here in terms of styling :)
