### ISSUE TITLE
unable to sign in - invitation expired

### ISSUE THREAD

**Issue by TannahG** [AVatch/uni-bug-tracker#3]
Hi, I tried to signup with Cornell email, but the page showed "Looks like this invitation is no longer valid or is not intended for your email." 
After that even though I managed to login, none of the buttons responds "+ideas", "people", etc.

**Comment by AVatch** [comment]
Hey there ! So you did sign in correct and are inside the Class future? The app just froze after sign in ?

**Comment by TannahG** [comment]
yes, I can sign in, but the page only shows menu and blank space. and no response from clicking anything on the page

**Comment by AVatch** [comment]
Ok cool - can you provide me with the email you signed up with and what browser you are using? You can email me if you like adrian@uni.fyi
