### ISSUE TITLE
announcements cut off

### ISSUE THREAD

**Issue by alicekamens** [AVatch/uni-bug-tracker#6]
in Uni, the announcement Greg posted cuts off towards the end, but there's no way to see the rest of the announcement - for example, clicking on Update doesn't take you to the full text. maybe there is a way to see the full text, but in any case it's not clear to me.

**Comment by AVatch** [comment]
Thanks! We are working on making the update card component more clear. It should open up a dialog w/ the full text body, but I believe the slider interferes w/ the click. 

This is a recurring issue w/ the slider component not allowing events to propagate down, so it's something high on my list to resolve. Thank you for pointing this out :)
