### ISSUE TITLE
ux for comments

### ISSUE THREAD

**Issue by alicekamens** [AVatch/uni-bug-tracker#7]
i left a follow up question for this idea - https://app.uni.fyi/future/137/feed?key=iU2. now when I visit that idea, i can see the little chat bubble with the number 3 next to it, indicating that there are three posts. i clicked that bubble many times trying to revisit my comment and see the other 2 comments but nothing was happening. eventually i tried clicking the chat bubble in the lower right hand corner, which did open up the previous posts, but that wasn't instinctual for me. my instinct was to click where the 3 comments were indicated to see the 3 comments.

**Comment by AVatch** [comment]
In the latest build the stat indicators now link to the appropriate tab in the post dialog. Thanks for the suggestion and pointing this out :)
